### ISSUE TITLE
re-render form not smooth

### ISSUE THREAD

**Issue by shamanking** [formio/react#119] opened 2018-06-26 09:02 UTC
When I re-render form of formio, it looks:

http://g.recordit.co/ZOX9ZDsAgw.gif

How can I make it smoother, or turn off loading when re-render

**Comment by randallknutson** [comment] 2018-08-02 18:14
Your linked image no longer exists. Can you describe what is happening?

**Comment by TanyaGashtold** [comment] 2023-08-31 12:48
I am closing the issue as it was created too long ago and there is no new comments here. If the issue is not resolved, please reopen it. Thanks!

**Closed by TanyaGashtold** 2023-08-31 12:48 UTC
