### ISSUE TITLE
PDF form builder not working

### ISSUE THREAD

**Issue by RY3777** [formio/react#353] opened 2020-11-26 05:26 UTC
<FormBuilder
        form={{ display: "pdf" }}
        onChange={(schema) => console.log(JSON.stringify(schema),setData(schema))}
        onSaveComponent ={(component)=>console.log(component)}
      /> 

1) This is only able to load the spinner instead of PDF in the form builder, is there any other alternate to load PDF. 
2) Also how to download the created form as a PDF .
Help us out on this, thanks in advance.

**Comment by wag110894** [comment] 2020-11-30 14:54
Hello @RY3777, 

PDF is only available using our Commerical platform and is not available in the open-source.
 Our commercial platform includes PDFs, multi-tenanted platform application ability, branded emails with templates, advanced conditional logic, webhook interfaces, and more.

If you are interested in learning more about or Commerical platform and features, please contact support@form.io.

**Comment by TanyaGashtold** [comment] 2023-08-31 13:45
I am closing the issue as it was created too long ago and there is no new comments here. If the issue is not resolved, please reopen it. Thanks!

**Closed by TanyaGashtold** 2023-08-31 13:45 UTC
Labels: bug
