### ISSUE TITLE
Wizard go to page event

### ISSUE THREAD

**Issue by SergeyMelnyk** [formio/react#356] opened 2020-12-08 08:29 UTC
Hello every one, can i do jump from 2 page wizard, to 5 for example, using one event, maybe like "goTo(5)"

**Comment by wag110894** [comment] 2020-12-08 21:16
Hello @SergeyMelnyk,

Thanks for reaching out! 

Are you wanting to accomplish this on the next button? You can also set your Wizard to enable breadcrumbs so that you can manually move from page 2 to 5. 

Let me know if this helps.

**Comment by SergeyMelnyk** [comment] 2020-12-09 06:53
@wag110894 thanks for your answer, but it is not what i need, i want disabled ny breadcrumbs for click, and on the last step i created custom component, where is all crouped information  from previous steps, and i created near this groups litl buton for edit information, this button must do 'redirect' or like gotTo() page

**Comment by travist** [comment] 2020-12-09 14:58
Inside of your custom component you can do the following which will have it go to certain pages.

```js
// Go to page 3.
this.root.setPage(3);
```

This can also be achieved in the Custom button component like this.

```js
instance.root.setPage(3);
```

**Comment by TanyaGashtold** [comment] 2023-08-31 13:46
I am closing the issue as it was created too long ago and there is no new comments here. If the issue is not resolved, please reopen it. Thanks!

**Closed by TanyaGashtold** 2023-08-31 13:46 UTC
Labels: bug
