### ISSUE TITLE
How to personalize alert message after 'Cancel even' on wizard ?

### ISSUE THREAD

**Issue by Nawfal07** [formio/react#364] opened 2020-12-25 09:54 UTC
## Environment
Please provide as many details as you can:
- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 4.3.0
- Formio.js version: 4.12.3
- Framework: React.js
- Browser: Firefox
- Browser version: 84.0

Hello there, I failed to find any Event Prop that would let me personalize the alert message displayed after you click 'Cancel' (That is supposed to reset data) in wizard mode.
![image](https://user-images.githubusercontent.com/18286778/103130872-c5aa9500-469e-11eb-9367-6dc73a43c506.png)

The default alert message is below:
![Screenshot from 2020-12-25 10-52-58](https://user-images.githubusercontent.com/18286778/103131087-9e07fc80-469f-11eb-9a25-3737f821f9c7.png)

Something like ```onCancel ``` or ```onReset``` would be useful.
Thanks for your help !

**Comment by travist** [comment] 2020-12-28 14:42
I am supportive of this change. You would just need to add an ```this.emit('cancel')``` around this line.

https://github.com/formio/formio.js/blob/master/src/Wizard.js#L707

if you create the pull request with this change, we will include it.

**Comment by TanyaGashtold** [comment] 2023-08-31 13:47
I am closing the issue as it was created too long ago and there is no new comments here. If the issue is not resolved, please reopen it. Thanks!

**Closed by TanyaGashtold** 2023-08-31 13:47 UTC
