### ISSUE TITLE
[react-formio] Sending values through parameters to selector component

### ISSUE THREAD

**Issue by acordobamo** [formio/react#403] opened 2021-07-05 08:35 UTC
Hello, I need to be able to send values by parameters (such as data source type, data source url, item template, etc ...) to the selector components, from my react code. How would it be possible? Thanks in advance.

**Comment by TanyaGashtold** [comment] 2023-08-31 13:51
I am closing the issue as it was created too long ago and there is no new comments here. If the issue is not resolved, please reopen it. Thanks!

**Closed by TanyaGashtold** 2023-08-31 13:51 UTC
Labels: bug
