### ISSUE TITLE
[BUG] Wizard. The set default value is not visible.

### ISSUE THREAD

**Issue by vaspaul** [formio/react#341] opened 2020-10-20 12:17 UTC
## Environment
- React-formio version: "^4.2.4"
- Formio.js version: "4.11.0"
- Frontend framework: React "^16.8.6"
- Browser: many browsers.
- Browser version: many browser versions.

## Steps to Reproduce
0. Create a wizard form, add the input component to it, and save.
1. Click "Edit" on the added input form component.
2. Set default value.
2.1. Mark some value as default.
2.2. Pay attention to the "Preview" section: the corresponding value is not change.
2.3. Press "Save" button for save changes and close this window.
3. In the previous step we change default value, **but now we don't see it here**.
4. Open the input component editing window again. Now we see that the corresponding value in the "Preview" changed.

P.S.: This bug occurs with the "Select Boxes", "Radio", "Text Field" and etc form componens.

## Expected behavior
- It is expected that when the default value is changed, the corresponding SelectBoxes in the "Preview" section will automatically change.
- When you click on the "Save" button, the "Select boxes" form component will be updated with the new default value.

## Observed behavior
- If you change the default value, the corresponding selection fields in the preview section **do not change automatically**.
- When you click on the "Save" button, the "Select boxes" form component **do not update with the new default value**.

## Example
Some code with "FormBuilder" component:
```js
...
import { Formio, FormBuilder } from 'react-formio';
...
render() {
    ...
    <FormBuilder
        form={my_var_with_form_schema}
        ...
    />
    ...
}
...
```

### Screens with error reproducing:
![step1](https://user-images.githubusercontent.com/46297009/96584397-d594aa00-12e6-11eb-89dd-af9066fceb3d.jpg)
![step2](https://user-images.githubusercontent.com/46297009/96584398-d62d4080-12e6-11eb-9818-053f919db22b.jpg)
![step3](https://user-images.githubusercontent.com/46297009/96584403-d6c5d700-12e6-11eb-89f1-bd007a022ba0.jpg)
![step4](https://user-images.githubusercontent.com/46297009/96584392-d3cae680-12e6-11eb-8e07-99ffbe9d8461.jpg)

**Comment by wag110894** [comment] 2020-10-23 19:05
Hello @vaspaul,

Thanks for reaching out!

We are aware of this issue and have resolved it in formio.js version 4.12.1-rc1.  I hope that this helps.

Have a great weekend.

**Comment by vaspaul** [comment] 2020-10-26 06:07
Hi, @wag110894 , 
Thank you for responding!

You know, I just tried changing the formio.js version for the following:

- 4.12.1-rc.1
- 4.12.1-rc.12
- 5.0.0-m.1
- 5.0.0-m.3

I saw the same thing on all of them - the bug is still reproduces.

**Comment by wag110894** [comment] 2020-10-28 20:29
@vaspaul, Can you provide what version of the formio app you are running on? You may need to upgrade that in order to see the difference.

**Comment by vaspaul** [comment] 2020-11-05 18:37
@wag110894 
I created a very simple react-app, just a demo:
```javascript
...
import { FormBuilder } from 'react-formio';
ReactDOM.render(
  <FormBuilder />,
  document.getElementById('root')
);
```
At the console you can see the versions that are being used:
![4 3 0_12 4 1-rc 1_console](https://user-images.githubusercontent.com/46297009/98281418-cd5a9100-1fad-11eb-89cf-b55843cb1be8.png)
With this versions, the bug still reproduces:
![4 3 0_12 4 1-rc 1_step1](https://user-images.githubusercontent.com/46297009/98281424-ce8bbe00-1fad-11eb-81c0-3baa3d8f720d.png)
![4 3 0_12 4 1-rc 1_step2](https://user-images.githubusercontent.com/46297009/98281428-cfbceb00-1fad-11eb-9874-23a61341b75f.png)


When I try to upgrade "formio.js" and "react-formio" versions to 5.0.0-m.1, an error appears:
![5 0 0-m1_console](https://user-images.githubusercontent.com/46297009/98281448-d51a3580-1fad-11eb-8d9a-f3299e90c86a.png)
![5 0 0-m1_error](https://user-images.githubusercontent.com/46297009/98281449-d5b2cc00-1fad-11eb-8790-5ec882148a0e.png)

**Comment by TanyaGashtold** [comment] 2023-08-31 13:44
I am closing the issue as it was created too long ago and there is no new comments here. If the issue is not resolved, please reopen it. Thanks!

**Closed by TanyaGashtold** 2023-08-31 13:44 UTC
Labels: bug
