### ISSUE TITLE
[BUG] Edit component's menu is not displayed properly when hovered

### ISSUE THREAD

**Issue by eblancperso** [formio/react#211] opened 2019-06-26 18:05 UTC
## Environment
- Hosting type
  - [ ] Form.io
  - [x] Local deployment
- Formio.js version: 4.0.0-beta.53
- Frontend framework: 4.0.0-beta.33
- Browser: Chrome
- Browser version: 75.0.3770.100 (Official Build) (64-bit)

## Steps to Reproduce
1. Create a new form
2. Drag and drop a component in the drop zone
3. Hover the added component

## Expected behavior
The edit menu should be displayed on top of the component.

## Observed behavior
The edit menu is displayed on top of the closest container.

## Example
https://codesandbox.io/s/frosty-borg-gudv8

![image](https://user-images.githubusercontent.com/13789373/60203757-563eb580-981b-11e9-8d10-33257de57ba0.png)

**Comment by randallknutson** [comment] 2019-06-26 20:49
I'm not seeing the same results. Are you including the css from formio.js? It might be some missing styles.

**Comment by eblancperso** [comment] 2019-06-26 21:07
Yes I am including the css. Did you check the codesandbox i’ve included in the bug? Maybe you can tell me what I’m doing wrong? Thank you! Awesome tool by the way!

**Comment by randallknutson** [comment] 2019-06-27 14:54
I wasn't able to run the codepen (It throws an error about invalid syntax).

**Comment by C1rdec** [comment] 2019-06-27 15:00
Hi, I'm experiencing the same issue. 
The **CodeSandBox** is working and showing the behavior.

**Comment by randallknutson** [comment] 2019-06-27 20:50
All of my environments appear to display this correctly. The issue is that there should be a position: relative around the component div to stop the reflow to the top of the page. For some reason that is missing. Can you check and see what the styling looks like?

**Comment by TanyaGashtold** [comment] 2023-08-31 13:15
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!

**Closed by TanyaGashtold** 2023-08-31 13:15 UTC
Labels: bug
