### ISSUE TITLE
[Question] How to add grid with submissions to this code

### ISSUE THREAD

**Issue by szymboro** [formio/react#398] opened 2021-06-16 15:10 UTC
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: 7.0.43
- Formio.js version: x
- Frontend framework: React
- Browser: Brave
- Browser version: latest

I think that I have tried everything...

For code or form JSON, please enclose in a code block:

```js
import React from "react";
import { Form } from "react-formio";

const report= (props) => {
  return (
    <>
      <Form {...props} src="https://example.form.io/report" />
    </>
  );
};

export default report;
```

**Comment by TanyaGashtold** [comment] 2023-08-31 13:51
I am closing the issue as it was created too long ago and there is no new comments here. If the issue is not resolved, please reopen it. Thanks!

**Closed by TanyaGashtold** 2023-08-31 13:50 UTC
Labels: bug
