### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by kapilgoyal6** [formio/react#366] opened 2021-01-06 06:31 UTC
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. When we tried to make any columns/table custom component, we extend the class from NestedComponent.
2. After that if we changed the type to our custom component such as "columnsCustomComp", then it works fine, but when we drag and drop any component in that columns component, it shows "undefined component"
3. 

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by wag110894** [comment] 2021-01-07 18:03
Hello @kapilgoyal6,

Can you provide a video of the issue taking place?

**Comment by TanyaGashtold** [comment] 2023-08-31 13:47
I am closing the issue as it was created too long ago and there is no new comments here. If the issue is not resolved, please reopen it. Thanks!

**Closed by TanyaGashtold** 2023-08-31 13:47 UTC
Labels: bug
