### ISSUE TITLE
Updating URL hostname in all forms of form io

### ISSUE THREAD

**Issue by pratikpbhagat** [formio/react#381] opened 2021-03-11 06:49 UTC
I have URL to pick up values in the form of json, with an ip address XXX, and now since the ip address has changed, I want to update the URL's in all the components and forms to YYY.

Is there a way to configure the URL hostname at a global level. 

![image](https://user-images.githubusercontent.com/7466629/110766005-bc32d100-827a-11eb-8cb1-e51ec5ebc459.png)

**Comment by travist** [comment] 2021-03-16 20:47
You can use the Public project configurations, add those public configurations to the form json, and then you can replace this with the following.

```
{{ config.baseUrl }}/GRC....
```

**Comment by pratikpbhagat** [comment] 2021-03-22 12:21
Can you please help me with some sample code to specify the public project configurations.

We are initializing the form io components as below.

`<Form src={this.formJson} onSubmit={this.submitData} onChange={(schema) => this.formIoChanged(schema)} />`

Where can I specify the configuration and pass it to the `formJson` as per the code above.

**Comment by travist** [comment] 2021-03-22 20:50
If you are not using our Enterprise solution, then you will need to manually add this to the Form JSON yourself within the "config" property of the form.

**Comment by TanyaGashtold** [comment] 2023-08-31 13:49
I am closing the issue as it was created too long ago and there is no new comments here. If the issue is not resolved, please reopen it. Thanks!

**Closed by TanyaGashtold** 2023-08-31 13:49 UTC
