### ISSUE TITLE
[BUG] Wizard Tabs beyond of the form, beyond of the screen.

### ISSUE THREAD

**Issue by vaspaul** [formio/react#338] opened 2020-10-18 18:29 UTC
## Environment

- Version: "^4.2.4"
- Formio.js version: 4.11.0
- Frontend framework: React
- Browser: all browsers all versions

## Steps to Reproduce
1. Create wizard form with many (20-30) tabs and long titles.
2. Invoke this form to display.

## Expected behavior
Expects to see a wizard form with scrollable tabs, something like this:
![Expected scrollable tabs. Something like this](https://i.stack.imgur.com/bUnK4.png)

## Observed behavior
Many tabs extend beyond the form and even beyond the screen, preventing you from clicking on those tabs beyond the screen:
![Tabs beyond the screen](https://user-images.githubusercontent.com/46297009/96376316-dc0c1000-1186-11eb-8ed8-ada91c851000.png)

## Example

Some code with "Form" component:
```js
...
import { Form, Formio } from 'react-formio';
...
render() {
    ...
    <Form
        form={there_is_my_var_with_form_schema}
        ...
    />
    ...
}
...
```
Result of rendering:
![Tabs beyond the screen](https://user-images.githubusercontent.com/46297009/96376316-dc0c1000-1186-11eb-8ed8-ada91c851000.png)

**Comment by TanyaGashtold** [comment] 2023-08-31 13:43
I am closing the issue as it was created too long ago and there is no new comments here. If the issue is not resolved, please reopen it. Thanks!

**Closed by TanyaGashtold** 2023-08-31 13:43 UTC
Labels: bug
