### ISSUE TITLE
Extending a existing component

### ISSUE THREAD

**Issue by Anandks1993** [formio/react#367] opened 2021-01-06 06:47 UTC
Hi, I have one requirement to override the existing `Signature` component. In which I need to show one Checkbox along with Signature component. Only if the Checkbox is ticked and Signature is drawn the field should be considered as a valid one in Form Renderer.

**Comment by travist** [comment] 2021-01-08 14:49
This shows how to extend a component.

https://formio.github.io/formio.js/app/examples/customcomponent.html

**Comment by Anandks1993** [comment] 2021-01-12 09:49
Thank you, I will check.

**Comment by TanyaGashtold** [comment] 2023-08-31 13:47
I am closing the issue as it was created too long ago and there is no new comments here. If the issue is not resolved, please reopen it. Thanks!

**Closed by TanyaGashtold** 2023-08-31 13:47 UTC
