### ISSUE TITLE
Using an external button and Hebrew name in API

### ISSUE THREAD

**Issue by Miros-iStore** [formio/react#554] opened 2024-02-05 23:27 UTC
1. I want to use the submit button outside the component, is this possible?
2. I write a name in Hebrew for the label and I get an error in the api tab that it is not possible to put a name in Hebrew and I have to change the name to English Is there something that can automatically convert the name to English or numbers

**Comment by brendanbond** [comment] 2024-02-07 03:03
1. Yes! Your button can emit an event that your application can subscribe to. 

2. What's the error?

**Comment by Miros-iStore** [comment] 2024-02-07 06:19
1. how it work? have in docs?
2. If I write in Hebrew on the display tab in the Label field,
api tab the Property name field is automatically filled with the same name(hebrew)

<img width="667" alt="Screenshot 2024-02-07 at 8 15 33" src="https://github.com/formio/react/assets/78298574/ff38be2b-6159-4b21-b484-0f847ea1d985">

**Comment by brendanbond** [comment] 2024-02-07 06:52
1. [Check out the event portion](https://help.form.io/userguide/form-building/form-components#button)

2. It's just like the error says - component keys are restricted to ASCII, I imagine to have to avoid dealing with unicode. That said, unicode strings should be supported in any other component field (labels, placeholder text, etc.)

I'm closing this issue for now as it's not a bug, but feel free to post in the repo's Discussions if you have any more questions.

**Closed** 2024-02-07 06:52 UTC

**Comment by Miros-iStore** [comment] 2024-02-29 23:24
I want use like this is this possible?
<img width="871" alt="Screenshot 2024-03-01 at 1 22 49" src="https://github.com/formio/react/assets/78298574/41403b07-89ba-47ca-b335-295b4f10bc5b">
