### ISSUE TITLE
[BUG] With Gatsby.JS, we get the error "document is not defined" on build

### ISSUE THREAD

**Issue by MalkyTheKid** [formio/react#329] opened 2020-08-25 01:04 UTC
We tried the basic example on the readme with our gatsby.js implementation.

Running it on `gatsby develop`, we do see the form and it is drawn fine. 
However when we do `gatsby build`, we get the following error:

```
 ERROR #95312 

"document" is not available during server side rendering.

See our docs page for more info on this error: https://gatsby.dev/debug-html


  867 | 
  868 | // IE >= 9
> 869 | 'function' === typeof document.createEvent ? function CustomEvent (type, params) {
      | ^
  870 |   var e = document.createEvent('CustomEvent');
  871 |   if (params) {
  872 |     e.initCustomEvent(type, params.bubbles, params.cancelable, params.detail);
```

Gatsby talks about document here:
https://www.gatsbyjs.com/docs/debugging-html-builds/

is there a proper way to run formIO in gatsby.js?

**Comment by wag110894** [comment] 2020-08-28 17:06
Hello @MalkyTheKid Thank you for reaching out!

We have added this item to our backlog. 

We welcome a pull request and also have a process to expedite this issue if you are interested.

If you are interested in expediting, please let us know and we can get the process started. For reference, the ticket number is FJS-1190.

Have a great day!

**Comment by MalkyTheKid** [comment] 2020-09-01 15:00
Hi Will (@wag110894),

How do we begin the process of expediting this item? (FJS-1190) 

We believe this could be useful especially with Gatsby JS on the rise

**Comment by wag110894** [comment] 2020-09-04 15:49
@MalkyTheKid 
Please reach out to support@form.io and let them know that you are interested in expediting FJS-1190.

**Comment by murrayw24** [comment] 2020-11-24 11:40
Hi there @wag110894 I just wondered if there is any update on this as it is also affecting us?

@MalkyTheKid did you manage to find a suitable workaround?

Thanks,
Murray

**Comment by wag110894** [comment] 2020-11-24 17:14
Hello @murrayw24, This item is still on our backlog.  As I mentioned above, we do welcome pull requests and also have a process to expedite this issue if you are interested.

If you are interested in expediting, please let us know by contacting support@form.io and we can get the process started.

**Comment by TanyaGashtold** [comment] 2023-08-31 13:42
I am closing the issue as it was created too long ago and there is no new comments here. If the issue is not resolved, please reopen it. Thanks!

**Closed by TanyaGashtold** 2023-08-31 13:42 UTC
