### ISSUE TITLE
How to advance page in a wizard without the next button?

### ISSUE THREAD

**Issue by jonathanlarav** [formio/react#347] opened 2020-11-11 21:59 UTC
I have a wizard with 3 pages, page1 has two buttons and it needs to advance to either page2 or page3 depending on which button is preset (the next, cancel and previous buttons are hidden)
Each button is publishing an event but I don't know how to use the event parameters to transition to the next page?
Is there a different way to address this?

**Comment by alexandraRamanenka** [comment] 2020-11-12 19:55
First of all, consider using Advanced Next Page option in the Page's settings. It allows to decide which page should be opened depending on some conditions. 
![image](https://user-images.githubusercontent.com/60643585/98988205-59356580-2538-11eb-90b0-b010a0642ab9.png)
If it is not applicable for your case, so you can set your buttons to execute custom actions instead of emitting an event. 
![image](https://user-images.githubusercontent.com/60643585/98989466-32782e80-253a-11eb-9f96-12b088094b8e.png)

**Comment by TanyaGashtold** [comment] 2023-08-31 13:45
I am closing the issue as it was created too long ago and there is no new comments here. If the issue is not resolved, please reopen it. Thanks!

**Closed by TanyaGashtold** 2023-08-31 13:45 UTC
