### ISSUE TITLE
Is `react-formio` npm package still needed?

### ISSUE THREAD

**Issue by mm-dsibinski** [formio/react#399] opened 2021-06-23 11:39 UTC
Hi guys,
I've been using the `react-formio` npm package (https://www.npmjs.com/package/react-formio) so far, but I noticed that there's a maintained one under `@formio/react` (https://www.npmjs.com/package/@formio/react).

For me it seems that https://www.npmjs.com/package/react-formio is not updated anymore.
Shouldn't this npm be removed or at least an information added on its npm page, that now https://www.npmjs.com/package/@formio/react should be used?

**Comment by TanyaGashtold** [comment] 2023-08-31 13:51
I am closing the issue as it was created too long ago and there is no new comments here. If the issue is not resolved, please reopen it. Thanks!

**Closed by TanyaGashtold** 2023-08-31 13:51 UTC

**Comment by mm-dsibinski** [comment] 2023-09-01 05:10
The question still remains. Shouldn't the  `react-formio` npm package (https://www.npmjs.com/package/react-formio) be removed or at least a note added there that there's a newer supported package?
