### ISSUE TITLE
[BUG] Uncaught TypeError: Cannot read property 'getUndoManager' of null  at w.endOperation (ace.js:1)

### ISSUE THREAD

**Issue by AgileFlex** [formio/react#292] opened 2020-03-24 12:22 UTC
## Environment
Please provide as many details as you can:
Uncaught TypeError: Cannot read property 'getUndoManager' of null  at w.endOperation (ace.js:1)
- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: **"formiojs": "^4.9.5",** | **"react-formio": "^4.3.0",**
- Frontend framework: **"react": "^16.12.0"**
- Browser: **Chrome**
- Browser version: **80.0.3987.149**

## Steps to Reproduce
1. Drag a component into the Formio Builder
2. 
3. 

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by randallknutson** [comment] 2020-03-24 14:36
This looks like a crash in the Ace editor. Can you see if it is a problem there instead of our platform?

**Comment by randallknutson** [comment] 2020-03-24 14:39
Looks like things may have changed recently with ace. We may need to look into what is wrong. This is another issue with ace just reported. https://github.com/formio/formio.js/issues/2569

**Comment by AgileFlexAgency** [comment] 2020-03-24 14:41
Hello @randallknutson 

The issue might be related to the fact that one js file is not loaded from the CDN: 

**ace.js:1 GET https://cdn.form.io/ace/1.4.8/theme-snow.js net::ERR_ABORTED 404**

Opening the URL above we see:
- Code: NoSuchKey
- Message: The specified key does not exist.
- Key: ace/1.4.8/theme-snow.js
- RequestId: AF392064C6DBF8AC
- HostId: ZegNZjSdRygLYkWOYWWYD05nUJX8tDRqOFWJCcB6dmwfpGNb62GKqAHsFbVyUNNaFUWt7y3nOKQ=

Hopefully it helps you pinpoint the issue. 

On the first load everything works fine. The issue can be replicated on dragging field on the FormBuilder.

Thank you.

**Comment by travist** [comment] 2020-03-24 21:30
theme-snow is not a valid theme for Ace. I believe this is probably caused by default wysiwyg settings (which were originally for the Quill editor) are somehow getting applied to Ace editor.

**Comment by AgileFlexAgency** [comment] 2020-04-01 08:25
@randallknutson @travist Thanks for investigating this bug. It does affect old versions of form.io too. Any progress on this one?

**Comment by jhen1422** [comment] 2020-04-01 14:09
@AgileFlexAgency 
This item is currently being worked on by our dev team. We are hoping to have a fix out by the end of this week or early next week.

**Comment by TanyaGashtold** [comment] 2023-08-31 13:31
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!

**Closed by TanyaGashtold** 2023-08-31 13:31 UTC
Labels: bug
