### ISSUE TITLE
recursion when using onChange

### ISSUE THREAD

**Issue by aminmc** [formio/react#386] opened 2021-03-26 08:48 UTC
See:

https://codesandbox.io/s/cra-react-formio-forked-tjs2l?file=/src/index.js

You can't add a new component when using onChange and try to set the state based on the new schema. This used to work before.

**Comment by travist** [comment] 2021-04-05 14:25
I can see that it falls into an infinite loop. Seems like a bug we need to look into.

**Comment by wag110894** [comment] 2021-04-07 16:01
For reference, the ticket number is FIO-2725.

**Comment by aminmc** [comment] 2021-04-21 07:06
@wag110894 Any updates on this?

**Comment by wag110894** [comment] 2021-04-26 15:39
Hello @aminmc,

Thank you for your patience while we discussed internally your ticket. We have added this to our backlog. We have a process to expedite this issue if you are interested. We have estimated that this will take 6 hours at $150/hour to resolve. 

Please let me know if you are interested and I can provide a formal quote.

Looking forward to your response.

Thank you.

**Comment by TanyaGashtold** [comment] 2023-08-31 13:49
I am closing the issue as it was created too long ago and there is no new comments here. If the issue is not resolved, please reopen it. Thanks!

**Closed by TanyaGashtold** 2023-08-31 13:49 UTC
Labels: bug
