### ISSUE TITLE
bundle.83f87edb05add5cf52bb.js:124 Uncaught TypeError: Failed to execute 'elementFromPoint' on 'Document': The provided double value is non-finite.

### ISSUE THREAD

**Issue by swetha2** [formio/react#237] opened 2019-08-13 06:54 UTC
Hi @all i'm getting this error when i'm trying to drag n drop a component. How can i resolve this error?

**Comment by randallknutson** [comment] 2019-08-13 14:41
I've seen this error when the element in the component is no longer in the dom. This usually happens either because a component redraw didn't update a reference to the dom element or something didn't work correctly. What version of the library are you currently using? Depending on the version, this might be fixed.

If you are on the latest 4.x rc build we may need an example for to debug what is going on.

**Comment by Romakita** [comment] 2019-08-27 08:34
Hello @randallknutson 

I have this issue also with 4.0.0-rc.18. It occurs randomly and broke ui :/

Thanks in advance for your help :)

**Comment by Romakita** [comment] 2019-08-27 15:01
Just when you dragndrop a component in formbuilder. We can have sometime the following error:

Uncaught TypeError: Failed to execute 'elementFromPoint' on 'Document': The provided double value is non-finite

After investigation, the problem caught by  `this.builder.instance.destroy(true)` (in FormBuilder.initializeBuilder ) and origin error come from dragulajs.

**Comment by Romakita** [comment] 2019-09-04 14:40
@jhen1422 Sorry for my late answer because effectively find a process to reproduce the bug is not easy.
We use the latest version 4.

So, to reproduce the, you have to follow theses steps:
- Create a new form (don't save the form)
- Fill a title for the new form (don't save the form)
- Dragndrop a component 
- The error should occur. The popin stay open but any actions are possible and the background app disappear. 

Here the stack trace:

```
index.js:1375 TypeError: Failed to execute 'elementFromPoint' on 'Document': The provided double value is non-finite.
    at getElementBehindPoint (dragula.js:710)
    at release (dragula.js:326)
    at Object.destroy (dragula.js:150)
    at WebformBuilder.detach (WebformBuilder.js:796)
    at WebformBuilder.destroy (Component.js:587)
    at FormBuilder.initializeBuilder (FormBuilder.jsx:43)
    at FormBuilder.componentWillReceiveProps (FormBuilder.jsx:73)
    at callComponentWillReceiveProps (react-dom.development.js:11873)
    at updateClassInstance (react-dom.development.js:12086)
    at updateClassComponent (react-dom.development.js:15271)
    at beginWork (react-dom.development.js:16262)
    at performUnitOfWork (react-dom.development.js:20279)
    at workLoop (react-dom.development.js:20320)
    at renderRoot (react-dom.development.js:20400)
    at performWorkOnRoot (react-dom.development.js:21357)
    at performWork (react-dom.development.js:21267)
    at performSyncWork (react-dom.development.js:21241)
    at requestWork (react-dom.development.js:21096)
    at scheduleWork (react-dom.development.js:20909)
    at Object.enqueueSetState (react-dom.development.js:11595)
```

**Comment by Romakita** [comment] 2019-09-04 15:04
I found a fix:

```javascript
// in FormBuilder.jsx
  onChange = () => {
    if (this.props.hasOwnProperty('onChange') && typeof this.props.onChange === 'function') {
      const form = {
        ...this.props.form,
        components: this.builder.instance.form.components // change only the components fields
      }

      this.props.onChange(form)
    }
  }
```
This fix avoid the componentWillReceiveProps call when you dragndrop a component.

I let you reproduce bug and apply the fix :)

See you
Romain

**Comment by Uysim** [comment] 2019-10-06 05:26
I use version 4.2.0 and have the same issue.
Anyone has it fixed yet?

**Comment by aminmc** [comment] 2019-10-06 09:07
Are you using react formio?

**Comment by Uysim** [comment] 2019-10-07 08:14
@aminmc I post the issue on react-formio repo. What do you think I should use?

**Comment by TanyaGashtold** [comment] 2023-08-31 13:20
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!

**Closed by TanyaGashtold** 2023-08-31 13:20 UTC
