### ISSUE TITLE
[BUG / UNEXPECTED BEHAVIOR] When editing the "label", the "value" changes too.

### ISSUE THREAD

**Issue by vaspaul** [formio/react#345] opened 2020-10-28 07:44 UTC
## Environment
- React-formio version: "^4.2.4"
- Formio.js version: "4.11.0"
- Frontend framework: React "^16.8.6"
- Browser: many browsers.
- Browser version: many browser versions.

## Steps to Reproduce
0. Create a form, add the "Select boxes" component to it.
1. Click "Edit" on the select boxes component.
2. Change the label.
3. Pay attention - the value is changed too.

## Expected behavior
- It is expected that when the "label" is changed, the corresponding "value" will not automatically change.
(Because I don't want to change the "value", I just want to fix the "label".)

## Observed behavior
- If you change the label value, the corresponding "value" will automatically change.

## Example:
![Pic1](https://user-images.githubusercontent.com/46297009/97406355-29684a00-190a-11eb-8ebb-aaea4187dbb9.png)
![Pic2](https://user-images.githubusercontent.com/46297009/97406358-2a00e080-190a-11eb-80aa-8c51224fb229.png)
![Pic3](https://user-images.githubusercontent.com/46297009/97406347-28371d00-190a-11eb-85dc-a616064f2c3a.png)

**Comment by alexandraRamanenka** [comment] 2020-10-29 07:22
This is how it's meant to work, values are calculated automatically  based on the Label field. You are able to manually change the value, but once you change the Label again, the Value will be recalculated.

**Comment by vaspaul** [comment] 2020-10-29 16:23
@alexandraRamanenka So this behavior is not a bug, but a pre-planned feature? To change this behavior you don't plan, it suits the developers. Did I get it right?

**Comment by alexandraRamanenka** [comment] 2020-10-29 17:03
Sure. It works in a such way by design. I know that it is not ideal, but we have have a list of items to discuss and improve in the 5th release.

**Comment by vaspaul** [comment] 2020-10-29 18:21
@alexandraRamanenka Will you discuss the question about this issue too? If there is, I would like to know the result of the developers ' discussion and decision on this issue.

**Comment by wag110894** [comment] 2020-10-30 18:48
Hello @vaspaul, we will definitely add this item to be discussed for places we could improve going into our 5x release.

**Comment by TanyaGashtold** [comment] 2023-08-31 13:44
I am closing the issue as it was created too long ago and there is no new comments here. If the issue is not resolved, please reopen it. Thanks!

**Closed by TanyaGashtold** 2023-08-31 13:44 UTC
Labels: bug
