### ISSUE TITLE
[BUG] "Data Grid" goes out of the "Panel"

### ISSUE THREAD

**Issue by vaspaul** [formio/react#365] opened 2020-12-25 13:06 UTC
## Environment
- React-formio version: 4.2.5
- Formio.js version: 4.11.0
- Frontend framework: React: 16.8.6
- Browser: many browsers
- Browser version: many browser versions

## The initial conditions:
There is a "Panel" component.
Inside this "Panel" component there is a "Data Grid" component.
Inside this "Data Grid" component, there is a "Select" component.
This "Select" component has one or more items with a long title.

## Steps to Reproduce
1. Choose the item with long title.

## Expected behavior
- It is expected that the "Data Grid" component will not goes out of the "Panel" component.

## Observed behavior
- After choosing the item with long title, "Data Grid" component goes out of the "Panel" component.

## Examples:
With a short title:
![Appearance with a short title](https://user-images.githubusercontent.com/46297009/103135360-d7a12d80-46c8-11eb-83aa-a2fe3ea09ea9.jpg)

With a long title:
![GoesOut1](https://user-images.githubusercontent.com/46297009/103135508-d9b7bc00-46c9-11eb-8880-9a2f2f479bc6.png)
![GoesOut2](https://user-images.githubusercontent.com/46297009/103135561-2c917380-46ca-11eb-9bb3-43ba7701e7ca.png)

**Comment by wag110894** [comment] 2021-01-08 20:17
Hello @vaspaul Can you provide a JSfiddle or the JSON of the form?

**Comment by TanyaGashtold** [comment] 2023-08-31 13:47
I am closing the issue as it was created too long ago and there is no new comments here. If the issue is not resolved, please reopen it. Thanks!

**Closed by TanyaGashtold** 2023-08-31 13:47 UTC
Labels: bug
